### ISSUE TITLE
Cell lib read issue in Read.cpp

### ISSUE THREAD

**Issue by ViennaPan** [ChairImpSec/PROLEAD#4]
When we using the PROLEAD to read  a new cell created below:
Gate
1
MUX3_X1
5
A B C S0 S1
1
Z
((not S0) and (not S1) and A) or (S0 and (not S1) and B) or (S1 and C)

We will see that the cell cannot be read correctly. The code in Read.cpp
            if (*pos != 0)
            {
                sprintf(Start, "I%d", Intermediate + CellType->Operations[i].NumberOfClauses + 1);
				strncpy(TempStr, End + 1, Max_Name_Length - 1);
				TempStr[Max_Name_Length - 1] = '\0';
				strcat(MyStr, TempStr);
            }

                CellType->Operations[i].NumberOfClauses++; // Fix the not() read bug
        } while (*pos != 0);
    }
Here is an bug that, after strcat(MyStr, TempStr), the char pointer pos address will inexpertly change.
I change the code as:
            if (*pos != 0)
            {
                sprintf(Start, "I%d", Intermediate + CellType->Operations[i].NumberOfClauses + 1);
				strncpy(TempStr, End + 1, Max_Name_Length - 1);
				TempStr[Max_Name_Length - 1] = '\0';
				strcat(MyStr, TempStr);
                CellType->Operations[i].NumberOfClauses++; // Fix the not() read bug
            }
            else
            {
                CellType->Operations[i].NumberOfClauses++; // Fix the not() read bug
                break;  // Fix the not() read bug 
	    }
            pos=MyStr;  // Fix the not() read bug */

        } while (*pos != 0);
    }
The issue is fixed. Please check. 
Thank you,
Vienna
NVIDIA.

**Comment by nicolaimueller** [comment]
Hi Vienna, 
Thanks for your comment. We checked your solution and integrated it.

Greetings, 
Nico
